# Fetches region-wide commodity prices from the Blizzard Game Data API and
# writes PriceData.lua into the Goldsmith addon folder. Run by a scheduled task
# (see Install-PriceTask.ps1). New data loads in game on the next login or /reload.
#
#   .\Fetch-PriceData.ps1 -SetCredentials   # once: store client ID and secret
#   .\Fetch-PriceData.ps1                   # fetch now

param(
    [switch]$SetCredentials,
    [string]$Region = 'us',
    [switch]$Force,     # write even if Blizzard hasn't published new data
    [string]$FromFile,  # testing: read a saved commodities JSON instead of calling the API
    [string]$OutFile    # testing: write somewhere other than the addon folder
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'   # the progress bar makes Invoke-WebRequest very slow in 5.1
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

$dataDir   = Join-Path $env:LOCALAPPDATA 'Goldsmith'
$credFile  = Join-Path $dataDir 'blizzard-api.xml'
$stateFile = Join-Path $dataDir 'last-modified.txt'
$logFile   = Join-Path $dataDir 'fetch.log'
$snapDir   = Join-Path $dataDir 'snapshots'
$addonDir  = Split-Path $PSScriptRoot -Parent
$outFile   = if ($OutFile) { $OutFile } else { Join-Path $addonDir 'PriceData.lua' }
$luac      = 'C:\Program Files (x86)\Lua\5.1\luac.exe'
$keepDays  = 14

New-Item -ItemType Directory -Force $dataDir, $snapDir | Out-Null

function Log($msg) {
    $line = '{0:yyyy-MM-dd HH:mm:ss}  {1}' -f (Get-Date), $msg
    Add-Content -Path $logFile -Value $line
    Write-Host $line
}

if ($SetCredentials) {
    # Stored with Windows DPAPI: only this Windows user on this PC can read it.
    $cred = Get-Credential -Message 'Blizzard API: user name = Client ID, password = Client Secret'
    $cred | Export-Clixml $credFile
    Write-Host "Saved to $credFile"
    return
}

try {
  if ($FromFile) {
    $json = [IO.File]::ReadAllText($FromFile)
    $lastModified = 'test'
  } else {
    if (-not (Test-Path $credFile)) { throw "No credentials. Run: .\Fetch-PriceData.ps1 -SetCredentials" }
    $cred   = Import-Clixml $credFile
    $id     = $cred.UserName
    $secret = $cred.GetNetworkCredential().Password

    # 1. OAuth token (client credentials flow)
    $basic = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("${id}:${secret}"))
    $token = (Invoke-RestMethod -Method Post -Uri 'https://oauth.battle.net/token' `
        -Headers @{ Authorization = "Basic $basic" } `
        -Body @{ grant_type = 'client_credentials' }).access_token

    # 2. Region-wide commodities (tens of MB, updated about hourly)
    $uri = "https://$Region.api.blizzard.com/data/wow/auctions/commodities?namespace=dynamic-$Region&locale=en_US"
    $resp = Invoke-WebRequest -UseBasicParsing -Uri $uri -Headers @{ Authorization = "Bearer $token" }
    $lastModified = $resp.Headers['Last-Modified']
    if (-not $Force -and (Test-Path $stateFile) -and (Get-Content $stateFile -Raw).Trim() -eq $lastModified) {
        Log "No new data (Last-Modified $lastModified)"
        return
    }
    $json = $resp.Content
    $resp = $null
  }

    # 3. Parse with a regex: ConvertFrom-Json in PowerShell 5.1 is very slow on files this size.
    #    Each auction: {"id":..,"item":{"id":ITEM},"quantity":QTY,"unit_price":PRICE,"time_left":".."}
    $rx = [regex]'"item":\{"id":(\d+)\},"quantity":(\d+),"unit_price":(\d+)'
    #    Per item: price -> units at that price, kept sorted by price.
    $items = New-Object 'System.Collections.Generic.Dictionary[int,System.Collections.Generic.SortedDictionary[long,long]]'
    $count = 0
    foreach ($m in $rx.Matches($json)) {
        $item = [int]$m.Groups[1].Value
        $qty = [long]$m.Groups[2].Value
        $price = [long]$m.Groups[3].Value
        $book = $null
        if (-not $items.TryGetValue($item, [ref]$book)) {
            $book = New-Object 'System.Collections.Generic.SortedDictionary[long,long]'
            $items[$item] = $book
        }
        $had = 0L
        [void]$book.TryGetValue($price, [ref]$had)
        $book[$price] = $had + $qty
        $count++
    }
    $json = $null
    if ($count -eq 0) { throw 'No auctions found in the response (format changed?)' }

    # 4. Stats per item (copper): lowest price, median by quantity, and the
    #    quantity-weighted average of the cheapest 15% of units ("market"), plus units listed.
    $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    $lua = New-Object Text.StringBuilder
    $csv = New-Object Text.StringBuilder
    [void]$lua.AppendLine('-- Generated by Tools\Fetch-PriceData.ps1. Do not edit.')
    [void]$lua.AppendLine("-- items[itemID] = { min, market, median, quantity }  (copper)")
    [void]$lua.AppendLine("GoldsmithPriceData = { region = `"$Region`", updated = $now, items = {")
    [void]$csv.AppendLine('item,min,market,median,quantity')
    $ids = New-Object 'System.Collections.Generic.List[int]' (, $items.Keys)
    $ids.Sort()
    foreach ($item in $ids) {
        $book = $items[$item]
        $total = 0L; foreach ($units in $book.Values) { $total += $units }
        $cut = [math]::Max(1, [math]::Ceiling($total * 0.15))
        $half = [math]::Ceiling($total / 2)
        $seen = 0L; $sum = 0.0; $taken = 0L; $median = $null; $min = $null
        foreach ($r in $book.GetEnumerator()) {
            if ($null -eq $min) { $min = $r.Key }
            if ($taken -lt $cut) {
                $n = [math]::Min($r.Value, $cut - $taken)
                $sum += $n * $r.Key; $taken += $n
            }
            $seen += $r.Value
            if ($null -eq $median -and $seen -ge $half) { $median = $r.Key; if ($taken -ge $cut) { break } }
        }
        $market = [long][math]::Round($sum / $taken)
        [void]$lua.AppendLine("[$item]={$min,$market,$median,$total},")
        [void]$csv.AppendLine("$item,$min,$market,$median,$total")
    }
    [void]$lua.AppendLine('} }')

    # 5. Write to a temp file, check it, then swap it in so WoW never loads half a file.
    $tmp = "$outFile.tmp"
    [IO.File]::WriteAllText($tmp, $lua.ToString(), (New-Object Text.UTF8Encoding $false))
    if (Test-Path $luac) {
        & $luac -p $tmp
        if ($LASTEXITCODE -ne 0) { throw 'Generated PriceData.lua failed the syntax check' }
    }
    Move-Item -Force $tmp $outFile

    if ($FromFile) { Log "TEST: $count auctions, $($items.Count) items -> $outFile"; return }

    # Keep hourly snapshots for price history later; drop old ones.
    $snap = Join-Path $snapDir ('{0:yyyy-MM-dd_HHmm}.csv' -f (Get-Date))
    [IO.File]::WriteAllText($snap, $csv.ToString())
    Get-ChildItem $snapDir -Filter *.csv | Where-Object LastWriteTime -lt (Get-Date).AddDays(-$keepDays) | Remove-Item

    Set-Content $stateFile $lastModified
    Log "OK: $count auctions, $($items.Count) items -> PriceData.lua (Last-Modified $lastModified)"
}
catch {
    Log "FAILED: $($_.Exception.Message)"
    exit 1
}
